//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Presence
    {
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> Entry_ { get; set; }
        public Nullable<System.DateTime> Exit_ { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
        public int Institution_Number { get; set; }
    }
}
