//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kindergarten
    {
        public int Institution_number { get; set; }
        public string Name_Kindergarten { get; set; }
        public string Adress_Kindergarten { get; set; }
        public string type_Kindergarten { get; set; }
    }
}
